import { callService } from '../api/rest';

// Minimal schema definitions for ha-signals
// This file is normally generated by running `npm run schema` from a live Home Assistant instance
// For development/testing without HA access, this minimal version provides the essential types

export type Domains = [
  {
    id: 'input_boolean';
    services: [
      {
        id: 'turn_on';
        target: EntityId | EntityId[];
        data: {};
      },
      {
        id: 'turn_off';
        target: EntityId | EntityId[];
        data: {};
      },
      {
        id: 'toggle';
        target: EntityId | EntityId[];
        data: {};
      },
    ];
  },
  {
    id: 'light';
    services: [
      {
        id: 'turn_on';
        target: EntityId | EntityId[];
        data: {
          brightness?: number;
          rgb_color?: [number, number, number];
        };
      },
      {
        id: 'turn_off';
        target: EntityId | EntityId[];
        data: {};
      },
    ];
  },
];

export type DomainId = keyof Entities;
export type ServiceId = Domains[number]['services'][number]['id'];
export type Domain<D extends DomainId> = Extract<Domains[number], { id: D }>;
export type Service<D extends DomainId, S extends ServiceId> = Extract<
  Domain<D>['services'][number],
  { id: S }
>;

// Entity type definitions
export type Entities = {
  ['input_boolean']: {
    entityId: `input_boolean.${string}`;
    attributes: Record<string, any>;
    state: string;
  };
  ['light']: {
    entityId: `light.${string}`;
    attributes: {
      brightness?: number;
      rgb_color?: [number, number, number];
    };
    state: string;
  };
  ['binary_sensor']: {
    entityId: `binary_sensor.${string}`;
    attributes: Record<string, any>;
    state: string;
  };
  ['sensor']: {
    entityId: `sensor.${string}`;
    attributes: Record<string, any>;
    state: string;
  };
};

export type EntityId = Entities[keyof Entities]['entityId'];
export type Attributes<D extends DomainId, E extends EntityId> = Extract<
  Entities[D],
  { entityId: E }
>['attributes'];

// Service helpers
export const InputBoolean = {
  turnOn: (target: EntityId | EntityId[], data?: {}) =>
    callService('input_boolean', 'turn_on', target, data),
  turnOff: (target: EntityId | EntityId[], data?: {}) =>
    callService('input_boolean', 'turn_off', target, data),
  toggle: (target: EntityId | EntityId[], data?: {}) =>
    callService('input_boolean', 'toggle', target, data),
};

export const Light = {
  turnOn: (
    target: EntityId | EntityId[],
    data?: { brightness?: number; rgb_color?: [number, number, number] }
  ) => callService('light', 'turn_on', target, data),
  turnOff: (target: EntityId | EntityId[], data?: {}) =>
    callService('light', 'turn_off', target, data),
};

// Device-related types (minimal for now)
export type DeviceName = string;
export type DeviceTriggers<D extends DeviceName> = string;
export const deviceNameMap = new Map<string, string>();

/**
 * Utility type that converts a union type to an intersection type.
 * Used to map entity IDs to their domains for type-safe entity access.
 */
type UnionToIntersection<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void
  ? I
  : never;

/**
 * Maps entity IDs to their corresponding domain types.
 * This allows TypeScript to infer the correct domain type from an entity ID.
 */
export type DomainForEntity = UnionToIntersection<
  {
    [Domain in keyof Entities]: {
      [EntityId in Entities[Domain]['entityId']]: Domain;
    };
  }[keyof Entities]
>;
